job:
  include:
    - jdk: openjdk11
      os: 
    - jdk: openjdk8
      os::
  allow_failures:
    - os: osx

script:
 - ./gradlew buildCore
    

Notifications:
  email:
    recipients:
      - s4muliub@uni-trier.de
    on_success: always
    on_failure: always

before_install:
  - gradle installWrapper

language: java

git:
  quiet: false
